services:
  - type: web
    name: gladbey
    env: static
    buildCommand: npm run build
    staticPublishPath: build
    routes:
      - src: /*
        dest: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
